### ISSUE TITLE
Flatten circular references

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/json-schema-ref-parser#22]
https://github.com/stoplightio/platform-internal/blob/fa5ef4a94ec892ba87050fad1ea66185ec9b2e20/packages/public-api/src/export/refs/resolve.ts#L111-L114

# Overview

Currently it's really hard to understand where a circular reference is happening, because if we ignore circular references and one exists the we unwind the current stack and set leave the original reference.

For example when resolving `kitchen-sink.v1.yaml` and specifically `indirect_circular_ref_file`, the original references is left in place because there is a circular ref from `kitchen-sink.v1.yaml` -> `indirect-circular.v1.yaml` -> `kitchen-sink.v1.yaml`.

`kitchen-sink.v1.yaml`

```yaml
title: Kitchen Sink
type: object
description: 'kitchen sink model test'
properties:
  basic_property:
    type: string
  simple_file_ref:
    $ref: ./simple.v1.yaml
  simple_file_as_http_ref_masked:
    $ref: 'http://stoplight-local.com:8080/api/v1/projects/bear/bear-cave/nodes/fixtures/simple.v1.yaml?mid=7'
  ref_to_self_as_file:
    $ref: ./kitchen-sink.v1.yaml
  ref_to_self_as_http:
    $ref: 'http://stoplight-local.com:8080/api/v1/projects/bear/bear-cave/nodes/fixtures/kitchen-sink.v1.yaml'
  ref_to_self_as_http_optomized_bundle:
    $ref: 'http://stoplight-local.com:8080/api/v1/projects/bear/bear-cave/nodes/fixtures/kitchen-sink.v1.yaml?deref=optimizedBundle'
  ref_to_self_as_http_with_mask_all_props:
    $ref: 'http://stoplight-local.com:8080/api/v1/projects/bear/bear-cave/nodes/fixtures/kitchen-sink.v1.yaml?deref=bundle&mid=8'
  indirect_circular_ref_file:
    $ref: ./indirect-circular.v1.yaml
  indirect_circular_ref_http:
    $ref: 'http://stoplight-local.com:8080/api/v1/projects/bear/bear-cave/nodes/fixtures/indirect-circular.v1.yaml'
  indirect_circular_ref_http_optomized_bundled:
    $ref: 'http://stoplight-local.com:8080/api/v1/projects/bear/bear-cave/nodes/fixtures/indirect-circular.v1.yaml?deref=optimizedBundle'
```

`indirect-circular.v1.yaml`

```ts
title: indirect-circular
type: object
properties:
  id:
    type: string
  circular_ref_as_file:
    $ref: ./kitchen-sink.v1.yaml
  circular_ref_back_as_http:
    $ref: http://stoplight-local.com:8080/api/v1/projects/bear/bear-cave/nodes/fixtures/kitchen-sink.v1.yaml
  circular_ref_back_as_http_optomized_bundle:
    $ref: http://stoplight-local.com:8080/api/v1/projects/bear/bear-cave/nodes/fixtures/kitchen-sink.v1.yaml?deref=optimizedBundle
```

## Proposal

Flatten circular references, so when resolving `kitchen-sink.v1.yaml` and specifically `indirect_circular_ref_file`, we replace `indirect_circular_ref_file` with the contents of `indirect-circular.v1.yaml`.

```ts
    dereference: {
       circular: 'flatten',
    },
```

Example result of flattening `indirect_circular_ref_file`

```yaml
  indirect_circular_ref_file:
      title: indirect-circular
    type: object
    properties:
      id:
        type: string
      circular_ref_as_file:
        $ref: ./kitchen-sink.v1.yaml
      circular_ref_back_as_http:
        $ref: http://stoplight-local.com:8080/api/v1/projects/bear/bear-cave/nodes/fixtures/kitchen-sink.v1.yaml
      circular_ref_back_as_http_optomized_bundle:
        $ref: http://stoplight-local.com:8080/api/v1/projects/bear/bear-cave/nodes/fixtures/kitchen-sink.v1.yaml?deref=optimizedBundle
```
